//
// RBPuddingWifiAnimail.h
// Generated by Core Animator version 1.3.1 on 16/9/10.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface RBPuddingWifiAnimail : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;


@property (nonatomic,copy) void(^puddingOpenAnimail)(void);
- (void)changeHandleLocation;
- (void)addWifiAnimail;
- (void)addSettingAnimail;
- (void)setUpAnimail;
- (void)addStartWifiAnimail;
- (void)showSendAnimails:(BOOL)flag;
// onpudding
- (void)addOnpuddingAnimation;
- (void)addOnpuddingAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addOnpuddingAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addOnpuddingAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addOnpuddingAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addOnpuddingMoveAnimation:(void (^)(BOOL finished))completionBlock;
- (void)removeOnpuddingAnimation;

- (void)removeAllAnimations;

- (void)cancleAnimail;
@end