//
//  Created by dongqiangliu on 18/01/16.
//  Copyright © 2018年 roobo. All rights reserved.
//

enum RBLogLevelTUTK {
  LOG_NONE    = -1,
  LOG_NORMAL  = 0,
  LOG_DEBUG   = 1,
  LOG_VERBOS  = 2,
};

enum MODE {
  MODE_SERVER   = 1,
  MODE_CLIENT   = 2,
};

enum AUTH_RESULT {
  AUTH_REJECT = 0,
  AUTH_GRANTED,
  AUTH_BYPASS,
};

enum EVENT_TYPE {
  NET_EVENT = 1,
  CLIENT_EVENT,
};

enum NET_EVENT {
  LOGINED = 0,
  LOGIN_FAIL,
  LOGIN_TIMEOUT,
  DEVICE_OFFLINE,
  UID_ERROR,
  CONNECTED,
  DISCONNECTED,
  NETWORK_ERROR,
  UNKOWN_ERROR,
};

enum CLIENT_EVENT {
  RECV_DATA_BEGIN = 1,
  REMOTE_BUSY,
  REMOTE_HANGUP,
  REQUEST_MICROPHONE,
  RELEASE_MICROPHONE,
  REQUEST_CAMERA,
  RELEASE_CAMERA,
  CLIENTS_NUM_CHANGE,
  VIDEORES_LOCKED,
};

enum RECORDER_EVENT {
  RECORDER_INIT_ERROR = 1,
  RECORDER_STARTED,
  RECORDER_STOPED,
  FILE_OUTPUT_ERROR,
};

enum RECORDER_ERROR {
  UNKNOWN_ERROR = 1,
  WAITING_VIDEO_TIMEOUT,
  VIDEO_STREAM_ERROR,
  CREATE_FILE_ERROR,
};

enum {
  CLIENT_START_SUCCESS,
  CLIENT_START_ERROR,
};
